name: Validate hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - name: hassfest validation
          uses: "home-assistant/actions/hassfest@master"